In [8]:
# lets create an np array and fill with random rgb values
import numpy as np
from PIL import Image

# create 4 x 6 array
a = np.zeros([4, 6, 3], dtype=np.uint8)

# fill with random rgb values
for i in range(4):
    for j in range(6):
        a[i, j, 0] = np.random.randint(0, 256)
        a[i, j, 1] = np.random.randint(0, 256)
        a[i, j, 2] = np.random.randint(0, 256)

# create an image from the array
img = Image.fromarray(a)
img.save('test.png')
img.show()

print(a)

[[[118 157 129]
  [167  53 113]
  [226  96 128]
  [ 34 127 107]
  [155 119   9]
  [159  72 168]]

 [[238  83 212]
  [ 50  77 150]
  [254 188 130]
  [117  32 249]
  [ 71 144  30]
  [167  48 188]]

 [[207  43 173]
  [156  47  29]
  [233 242   6]
  [238 210 153]
  [117  10 112]
  [202 248 251]]

 [[ 96 183  72]
  [ 92 236  48]
  [ 54 165  23]
  [ 63  39 182]
  [243 234 126]
  [ 32 223  99]]]


In [26]:
# load image from file
img = Image.open('loadtest.png')
a = np.array(img)
#print(a)
# average the every group of 4 pixels
image_size = a.shape
print(image_size)
# create a new array to store the averaged values
b = np.zeros([int(image_size[0]/2), int(image_size[1]/2), 3], dtype=np.uint8)

def avg_image(image, image_size):
    b = np.zeros([int(image_size[0]/2), int(image_size[1]/2), 3], dtype=np.uint8)
    for i in range(0, image_size[0], 2):
        for j in range(0, image_size[1], 2):
            b[int(i/2), int(j/2), 0] = (int(a[i, j, 0]) + int(a[i+1, j, 0]) + int(a[i, j+1, 0]) + int(a[i+1, j+1, 0])) / 4
            b[int(i/2), int(j/2), 1] = (int(a[i, j, 1]) + int(a[i+1, j, 1]) + int(a[i, j+1, 1]) + int(a[i+1, j+1, 1])) / 4
            b[int(i/2), int(j/2), 2] = (int(a[i, j, 2]) + int(a[i+1, j, 2]) + int(a[i, j+1, 2]) + int(a[i+1, j+1, 2])) / 4

    return b
    # create an image from the array

b = avg_image(a, image_size)
img = Image.fromarray(b)
img.save('averaged.png')
img.show()
print(b)

(500, 500, 3)
[[[125 162 154]
  [125 162 154]
  [124 161 153]
  ...
  [122 162 153]
  [125 162 154]
  [125 162 154]]

 [[125 162 154]
  [125 162 154]
  [124 161 153]
  ...
  [122 162 153]
  [125 162 154]
  [125 162 154]]

 [[125 162 154]
  [125 162 154]
  [124 161 153]
  ...
  [122 162 153]
  [124 161 153]
  [124 161 153]]

 ...

 [[122 162 155]
  [122 162 155]
  [122 162 155]
  ...
  [122 160 154]
  [124 161 155]
  [124 161 155]]

 [[122 160 152]
  [122 160 152]
  [122 160 152]
  ...
  [122 160 154]
  [122 162 155]
  [122 162 155]]

 [[122 160 152]
  [122 160 152]
  [122 160 152]
  ...
  [122 160 154]
  [122 162 155]
  [122 162 155]]]


In [27]:
# only keep the most dominant rgb value of the group of 4 pixels

def dominant_image(image, image_size):
    a = image
    b = np.zeros([int(image_size[0]/2), int(image_size[1]/2), 3], dtype=np.uint8)
    for i in range(0, image_size[0], 2):
        for j in range(0, image_size[1], 2):
            b[int(i/2), int(j/2), 0] = max(int(a[i, j, 0]), int(a[i+1, j, 0]), int(a[i, j+1, 0]), int(a[i+1, j+1, 0]))
            b[int(i/2), int(j/2), 1] = max(int(a[i, j, 1]), int(a[i+1, j, 1]), int(a[i, j+1, 1]), int(a[i+1, j+1, 1]))
            b[int(i/2), int(j/2), 2] = max(int(a[i, j, 2]), int(a[i+1, j, 2]), int(a[i, j+1, 2]), int(a[i+1, j+1, 2]))

    return b

b = dominant_image(a, image_size)
img = Image.fromarray(b)
img.save('dominant.png')
img.show()
print(b)

[[[125 162 154]
  [125 162 154]
  [124 161 153]
  ...
  [122 162 153]
  [125 162 154]
  [125 162 154]]

 [[125 162 154]
  [125 162 154]
  [124 161 153]
  ...
  [122 162 153]
  [125 162 154]
  [125 162 154]]

 [[125 162 154]
  [125 162 154]
  [124 161 153]
  ...
  [122 162 153]
  [124 161 153]
  [124 161 153]]

 ...

 [[122 162 155]
  [122 162 155]
  [122 162 155]
  ...
  [122 160 154]
  [124 161 155]
  [124 161 155]]

 [[122 160 152]
  [122 160 152]
  [122 160 152]
  ...
  [122 160 154]
  [122 162 155]
  [122 162 155]]

 [[122 160 152]
  [122 160 152]
  [122 160 152]
  ...
  [122 160 154]
  [122 162 155]
  [122 162 155]]]


In [28]:
# remove channels with the lowest value

def remove_channel(image, image_size):
    a = image
    b = np.zeros([int(image_size[0]/2), int(image_size[1]/2), 3], dtype=np.uint8)
    for i in range(0, image_size[0], 2):
        for j in range(0, image_size[1], 2):
            b[int(i/2), int(j/2), 0] = max(int(a[i, j, 0]), int(a[i+1, j, 0]), int(a[i, j+1, 0]), int(a[i+1, j+1, 0]))
            b[int(i/2), int(j/2), 1] = max(int(a[i, j, 1]), int(a[i+1, j, 1]), int(a[i, j+1, 1]), int(a[i+1, j+1, 1]))
            b[int(i/2), int(j/2), 2] = max(int(a[i, j, 2]), int(a[i+1, j, 2]), int(a[i, j+1, 2]), int(a[i+1, j+1, 2]))

    return b

b = remove_channel(a, image_size)
img = Image.fromarray(b)
img.save('remove_channel.png')
img.show()
print(b)

[[[125 162 154]
  [125 162 154]
  [124 161 153]
  ...
  [122 162 153]
  [125 162 154]
  [125 162 154]]

 [[125 162 154]
  [125 162 154]
  [124 161 153]
  ...
  [122 162 153]
  [125 162 154]
  [125 162 154]]

 [[125 162 154]
  [125 162 154]
  [124 161 153]
  ...
  [122 162 153]
  [124 161 153]
  [124 161 153]]

 ...

 [[122 162 155]
  [122 162 155]
  [122 162 155]
  ...
  [122 160 154]
  [124 161 155]
  [124 161 155]]

 [[122 160 152]
  [122 160 152]
  [122 160 152]
  ...
  [122 160 154]
  [122 162 155]
  [122 162 155]]

 [[122 160 152]
  [122 160 152]
  [122 160 152]
  ...
  [122 160 154]
  [122 162 155]
  [122 162 155]]]


In [30]:
# only keep the most dominant rgb value and channel of the group of 4 pixels

def dominant_channel_image(image, image_size):
    a = image
    b = np.zeros([int(image_size[0]/2), int(image_size[1]/2), 3], dtype=np.uint8)
    for i in range(0, image_size[0], 3):
        for j in range(0, image_size[1], 3):
            b[int(i/2), int(j/2), 0] = max(int(a[i, j, 0]), int(a[i+1, j, 0]), int(a[i, j+1, 0]), int(a[i+1, j+1, 0]))
            b[int(i/2), int(j/2), 1] = max(int(a[i, j, 1]), int(a[i+1, j, 1]), int(a[i, j+1, 1]), int(a[i+1, j+1, 1]))
            b[int(i/2), int(j/2), 2] = max(int(a[i, j, 2]), int(a[i+1, j, 2]), int(a[i, j+1, 2]), int(a[i+1, j+1, 2]))
            if b[int(i/2), int(j/2), 0] == int(a[i, j, 0]):
                b[int(i/2), int(j/2), 1] = 0
                b[int(i/2), int(j/2), 2] = 0
            elif b[int(i/2), int(j/2), 1] == int(a[i, j, 1]):
                b[int(i/2), int(j/2), 0] = 0
                b[int(i/2), int(j/2), 2] = 0
            else:
                b[int(i/2), int(j/2), 0] = 0
                b[int(i/2), int(j/2), 1] = 0

    return b

b = dominant_channel_image(a, image_size)
img = Image.fromarray(b)